name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential
    - name: Prepare cmake
      run: cmake .
    - name: Build
      run: make -j $(nproc)
    - name: Test
      working-directory: test_travis/
      run: |
        set -eux
        ./test.sh
